os: linux
dist: xenial

language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules

services:
  - docker-compose

before_install:
  - git clone --branch=master https://github.com/BurhanH/automaton-v7.git automaton-v7 

script:
- cd automaton-v7
- pwd
- ls -lah
# - docker-compose --version
# - docker-compose up -d
# here our test
# - docker-compose down 
