os: linux
dist: bionic

language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules

services:
  - docker-compose

before_install:
  # Cloning  a test automation framework
  - git clone --branch=master https://github.com/BurhanH/automaton-v7.git automaton-v7 
  - cd automaton-v7
  # Changing some parameters like browser and grid use
  - sed -i 's/firefox,/chrome,/' /home/travis/build/BurhanH/automaton-v16/automaton-v7/config.js
  - sed -i 's/false,/true,/' /home/travis/build/BurhanH/automaton-v16/automaton-v7/config.js
  # Creating a virtual Selenium Grid infrastructure with Hub and 2 browsers, Chrome and Firefox 
  - docker-compose --version
  - docker-compose up -d
  - sleep 15 # Giving some time for Selenium Grid to up

script:
  - npm test
  - docker-compose down
