os: linux
dist: xenial

language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules

services:
  - docker-compose

before_install:
  - git clone --branch=master https://github.com/BurhanH/automaton-v7.git automaton-v7 
  - cd automaton-v7
  - pwd
  - ls -lah
  - sed 's/false,/true,/' /home/travis/build/BurhanH/automaton-v16/automaton-v7/config.js
  - cat config.js

script:
# - docker-compose --version
# - docker-compose up -d
- npm test
# - docker-compose down 
